export const ROUTE_NAMES = {
  // Admin routes
  ADMIN_DASHBOARD: 'AdminLandingPage',
  ADMIN_DOER_LIST: 'AdminWorkerPage',
  ADMIN_MISSION_AD: 'AdminMissionAd',
  ADMIN_MISSION_CANDIDATE_LIST: 'AdminCandidatesList',
  ADMIN_MISSION_EDIT: 'AdminMissionInfoPageEdit',
  ADMIN_MISSION_LIST: 'AdminMissionPage',
  ADMIN_MISSION_QUIZZ: 'AdminMissionQuizzPage',
  ADMIN_MISSION_READ: 'AdminMissionInfoPage',

  // Client routes
  CLIENT_CANDIDATES_PAGE: 'CLIENT_CANDIDATES_PAGE',
  CLIENT_CHECKOUT_FAILURE: 'CLIENT_CHECKOUT_FAILURE',
  CLIENT_CHECKOUT_SUCCESS: 'CLIENT_CHECKOUT_SUCCESS',
  CLIENT_DASHBOARD_TUTORIAL_PAGE: 'CLIENT_DASHBOARD_TUTORIAL_PAGE',
  CLIENT_FAQ_PAGE: 'CLIENT_FAQ_PAGE',
  CLIENT_LOGIN: 'CLIENT_LOGIN',
  CLIENT_RECRUITMENT_PROCESS_PAGE: 'CLIENT_RECRUITMENT_PROCESS_PAGE',

  WEBVIEW_MISSION: 'WEBVIEW_MISSION',
};
