export const ROUTE_NAMES = {
  // Client routes
  CLIENT_APP: 'CLIENT_APP',
  CLIENT_CANDIDATES_PAGE: 'CLIENT_CANDIDATES_PAGE',
  CLIENT_CHECKOUT_FAILURE: 'CLIENT_CHECKOUT_FAILURE',
  CLIENT_CHECKOUT_SUCCESS: 'CLIENT_CHECKOUT_SUCCESS',
  CLIENT_DASHBOARD_TUTORIAL_PAGE: 'CLIENT_DASHBOARD_TUTORIAL_PAGE',
  CLIENT_FAQ_PAGE: 'CLIENT_FAQ_PAGE',
  CLIENT_LOGIN: 'CLIENT_LOGIN',
  CLIENT_RECRUITMENT_PROCESS_PAGE: 'CLIENT_RECRUITMENT_PROCESS_PAGE',

  WEBVIEW_MISSION: 'WEBVIEW_MISSION',
};
