export enum MissionStatus {
  FOR_VALIDATION = 'FOR_VALIDATION',
  TO_BE_PAID_BY_CLIENT = 'TO_BE_PAID_BY_CLIENT',
  BEING_PREPARED = 'BEING_PREPARED',
  PREPARED = 'PREPARED',
  ON_GOING = 'ON_GOING',
  BEING_REVIEWED = 'BEING_REVIEWED',
  DOERS_TO_BE_PAID = 'WORKERS_TO_BE_PAID',
  DONE = 'DONE',
}
