'use strict'

let AttributesEnum = {
  FIRST_NAME: 'FIRST_NAME',
  LAST_NAME: 'LAST_NAME',
  EMAIL: 'EMAIL',
  GENDER: 'GENDER',
  BIRTHDAY: 'BIRTHDAY',
  COUNTRY: 'COUNTRY',
  CITY: 'CITY',
  NATIONALITY: 'NATIONALITY',
  DEPARTMENT: 'DEPARTMENT',
  ADDRESS: 'ADDRESS',
  PHONE: 'PHONE',
  SIRET: 'SIRET',
  RESIDENCE_PERMIT_OK: 'RESIDENCE_PERMIT_OK'
}

Object.freeze(AttributesEnum)

module.exports = AttributesEnum
