'use strict';

let Enum = {
  WORKER_ALREADY_APPLIED_OR_HIRED: 'WORKER_ALREADY_APPLIED_OR_HIRED',
  MISSION_ALREADY_PREPARED: 'MISSION_ALREADY_PREPARED',
  MISSION_ALREADY_REVIEWED: 'MISSION_ALREADY_REVIEWED',
};

Object.freeze(Enum);

module.exports = Enum;
