export const COMPONENTS_NAMES = {
  // Common components
  CHIP: 'hd-chip',
  FORM_CHIPS: 'hd-chips',
  IMAGE_ASPECT_RATIO: 'hd-image-aspect-ratio',
  PAGE: 'hd-page',
  TIMEBAR: 'hd-timebar',
  VIDEO: 'hd-video',
  HEART_BUTTON: 'hd-heart-button',
  MENU_ITEM: 'hd-menu-item',
  PLAY_BUTTON: 'hd-play-button',
  EMOJI: 'hd-emoji',

  // Admin components
  ADMIN_CONTACT_INFORMATION_FORM: 'hd-contact-information-form',
  ADMIN_CREDIT_CARD_PAIEMENT: 'hd-credit-card-paiement',
  ADMIN_DIALOG_CONFIRM: 'hd-dialog-confirm',
  ADMIN_ENTERPRISE_INFORMATION_FORM: 'hd-enterprise-information-form',
  ADMIN_IMAGE_MESSAGE_FORM: 'hd-image-message-form',
  ADMIN_MISSION: 'hd-mission',
  ADMIN_MISSION_CREATION_PROCESS: 'hd-mission-creation-process',
  ADMIN_MISSION_ENTERPRISE_FORM: 'hd-enterprise-information-form',
  ADMIN_MISSION_INFORMATION_FORM: 'hd-mission-information-form',
  ADMIN_MISSION_INFORMATION_STEP: 'hd-mission-information-step',
  ADMIN_QUESTION_DIALOG_FORM: 'hd-question-dialog-form',
  ADMIN_QUESTION_FORM: 'hd-question-form',
  ADMIN_QUESTION_PREVIEW: 'hd-question-preview',
  ADMIN_QUESTION_SEARCH_DIALOG: 'hd-question-search-dialog',
  ADMIN_QUICK_REPLIES_MESSAGE_FORM: 'hd-quick-replies-message-form',
  ADMIN_QUIZZ_EMPTY_STATE: 'hd-quizz-empty-state',
  ADMIN_QUIZZ_FORM: 'hd-quizz-form',
  ADMIN_TEXT_MESSAGE_FORM: 'hd-text-message-form',

  // Client dashboard components
  CLIENT_ACTION_LIST_ITEM: 'hd-action-list-item',
  CLIENT_CANDIDATE_LIST: 'hd-candidate-list',
  CLIENT_CANDIDATE_VIDEO_CV_SECTION: 'hd-candidate-video-cv-section',
  CLIENT_CANDIDATE_LIST_ITEM: 'hd-candidate-list-item',
  CLIENT_CARD_DIALOG: 'hd-card-dialog',
  CLIENT_DIALOG: 'hd-dialog',
  CLIENT_INFO_CARD: 'hd-info-card',
  CLIENT_INFO_PAGE_LAYOUT: 'hd-info-page-layout',
  CLIENT_MENU_BUTTON: 'hd-menu-button',
  CLIENT_MISSION_INFO_CARD: 'hd-mission-info-card',
  CLIENT_MISSION_INFO_ACTION_BUTTON: 'hd-mission-info-action-button',
  CLIENT_PAGE_MENU: 'hd-page-menu',
  CLIENT_SPONSO_MY_AD_DIALOG: 'hd-sponso-my-ad-dialog',
  CLIENT_BOOST_MY_AD_DIALOG: 'hd-boost-my-ad-dialog',
  CLIENT_HELP_DIALOG: 'hd-help-dialog',
};
